### ISSUE TITLE
CSS class is missing with tarteaucitron v1.9.6 (20220322)

### ISSUE THREAD

**Issue by pegasnier** [GouvernementFR/dsfr-theme-tarteaucitron#2]
To improve accessibility, a new class has been added to tarteaucitron header [refer this commit](https://github.com/AmauriC/tarteaucitron.js/commit/0d3dd2d6ad9b173088ee3d7d229de5d249993d0c).

With actual css definition, the div for accessibility stays visible on top of the page (1st element of the body).

The following css is provided by @AmauriC:
```css
.tac_visually-hidden {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap; /* added line */
      border: 0;
}
```
